//arrays

const products = [
    {
        id:1,
        nombre: "Torta Red Velvet",
        imagen: "1.jpg",
        alt: "Red Velvet",
        precio: 4900,
    },
    {
        id:2,
        nombre: "Torta Marquise",
        imagen: "assets/img/marquise.jpg",
        alt: "Marquise",
        precio: 2200,
    },
    {
        id:3,
        nombre: "Torta Rogel",
        imagen: "assets/img/rogel.jpg",
        alt: "Rogel",
        precio: 2500,
    },
    {
        id:4,
        nombre: "Torta Matilda",
        imagen: "assets/img/torta matilda.jpg",
        alt: "Matilda",
        precio: 2000,
    },
    {
        id:5,
        nombre: "Batido durazno",
        imagen: "assets/img/batido-Durazno.jpg",
        alt: "Batido de durazno",
        precio: 2100,
    },
    {
        id:6,
        nombre: "Batido frutilla",
        imagen: "assets/img/batido-Frutilla.jpg",
        alt: "Batido de frutilla",
        precio: 2900,
    },
    {
        id:7,
        nombre: "batido de kiwi",
        imagen: "assets/img/batido-Kiwi.jpg",
        alt: "Batido de kiwi",
        precio: 3000,
    },
    {
        id:8,
        nombre:"Batido sandia",
        imagen: "assets/img/batido-Sandia.jpg",
        alt: "Batido de sandia",
        precio: 2300,
    },
    {
        id:9,
        nombre: "Helado de Cafe",
        imagen: "assets/img/helado-Cafe.jpg",
        alt: "Helado de cafe",
        precio: 1000,

    },
    {
        id:10,
        nombre: "Helado chocolate",
        imagen: "assets/img/helado-Chocolate.jpg",
        alt: "Helado de Chocolate",
        precio: 2000,
    },
    {
        id:11,
        nombre: "Helado de coco",
        imagen: "assets/img/helado-Coco.jpg",
        alt: "Helado de coco",
        precio: 1900,
    },
    {
        id:12,
        nombre: "Helado vainilla",
        imagen: "assets/img/helado-Vainilla.jpg",
        alt: "Helado de vainilla",
        precio: 1500,
    },
    {
        id: 13,
        nombre: "Helado de frutilla",
        imagen: "assets/img/helado-frutilla.jpg",
        alt: "Helado de frutilla",
        precio: 2100,
    },
    {
        id: 14,
        nombre: "Torta Selva Negra",
        imagen: "assets/img/torta-selva-negra.jpg",
        alt: "Torta Selva Negra",
        precio: 3500,
    },
    {
        id: 15,
        nombre: "Batido de banana",
        imagen: "assets/img/batido-banana.jpg",
        alt: "Batido de banana",
        precio: 2200,
    },
    {
        id: 16,
        nombre: "Helado de limón",
        imagen: "assets/img/helado-limon.jpg",
        alt: "Helado de limón",
        precio: 1900,
    },
    {
        id: 17,
        nombre: "Torta Cheesecake",
        imagen: "assets/img/torta-cheesecake.jpg",
        alt: "Torta Cheesecake",
        precio: 4000,
    },
    {
        id: 18,
        nombre: "Batido de mango",
        imagen: "assets/img/batido-mango.jpg",
        alt: "Batido de mango",
        precio: 2400,
    }

];
